
echo "installing sharp..."
g++ -o bin/sharpc -std=c++11 -pthread -lstdc++ -O3 -Ofast -g main.cpp stdimports.h -DMAKE_COMPILER lib/grammar/*.h lib/grammar/*.cpp lib/grammar/json/*.h lib/grammar/json/*.cpp lib/grammar/settings/*.h lib/grammar/settings/*.cpp lib/grammar/frontend/tokenizer/*.h lib/grammar/frontend/tokenizer/*.cpp lib/grammar/frontend/parser/*.h lib/grammar/frontend/parser/*.cpp lib/grammar/frontend/*.h lib/grammar/frontend/*.cpp lib/grammar/taskdelegator/*.h lib/grammar/taskdelegator/*.cpp lib/grammar/backend/dependency/*.h lib/grammar/backend/dependency/*.cpp lib/grammar/backend/preprocessor/*.h lib/grammar/backend/preprocessor/*.cpp lib/grammar/backend/postprocessor/*.h lib/grammar/backend/postprocessor/*.cpp lib/grammar/backend/astparser/*.h lib/grammar/backend/astparser/*.cpp lib/grammar/backend/context/*.h lib/grammar/backend/context/*.cpp lib/grammar/backend/compiler/*.h lib/grammar/backend/compiler/*.cpp lib/grammar/backend/compiler/expressions/*.h lib/grammar/backend/compiler/expressions/*.cpp lib/grammar/backend/compiler/expressions/binary/*.h lib/grammar/backend/compiler/expressions/binary/*.cpp lib/grammar/backend/compiler/expressions/primary/*.h lib/grammar/backend/compiler/expressions/primary/*.cpp lib/grammar/backend/compiler/expressions/unary/*.h lib/grammar/backend/compiler/expressions/unary/*.cpp lib/grammar/backend/operation/*.h lib/grammar/backend/operation/*.cpp lib/grammar/backend/*.h lib/grammar/backend/*.cpp lib/grammar/backend/types/*.h lib/grammar/backend/types/*.cpp lib/grammar/backend/compiler/di/*.h lib/grammar/backend/compiler/di/*.cpp lib/grammar/backend/compiler/functions/*.h lib/grammar/backend/compiler/functions/*.cpp lib/grammar/backend/compiler/functions/statements/*.h lib/grammar/backend/compiler/functions/statements/*.cpp lib/grammar/backend/finalizer/*.h lib/grammar/backend/finalizer/*.cpp lib/grammar/backend/finalizer/optimization/*.h lib/grammar/backend/finalizer/optimization/*.cpp lib/grammar/backend/finalizer/optimization/codemotion/*.h lib/grammar/backend/finalizer/optimization/codemotion/*.cpp lib/grammar/backend/finalizer/optimization/analyzer/*.h lib/grammar/backend/finalizer/optimization/analyzer/*.cpp lib/grammar/backend/finalizer/optimization/processor/*.h lib/grammar/backend/finalizer/optimization/processor/*.cpp lib/grammar/backend/finalizer/generation/*.h lib/grammar/backend/finalizer/generation/*.cpp lib/grammar/backend/finalizer/generation/code/*.h lib/grammar/backend/finalizer/generation/code/*.cpp lib/grammar/backend/finalizer/generation/obfuscation/*.h lib/grammar/backend/finalizer/generation/obfuscation/*.cpp lib/grammar/backend/finalizer/generation/code/scheme/*.h lib/grammar/backend/finalizer/generation/code/scheme/*.cpp lib/util/*.cpp lib/util/zip/*.cpp lib/core/*.cpp lib/core/*.h lib/core/opcode/*.cpp lib/core/opcode/*.h 
sudo cp bin/sharpc /bin

echo "installing runtime support..."
g++ -o bin/sharp -std=c++11 -pthread -lstdc++ -lm -lrt -lstdc++ -O3 -ldl -mno-red-zone -g -Ofast main.cpp stdimports.h lib/runtime/error/*.h lib/runtime/error/*.cpp lib/runtime/exe/*.h lib/runtime/exe/*.cpp lib/runtime/memory/*.h lib/runtime/memory/*.cpp lib/runtime/reflect/*.h lib/runtime/reflect/*.cpp lib/runtime/snb/*.h lib/runtime/snb/*.cpp lib/runtime/multitasking/*/*.h lib/runtime/multitasking/*/*.cpp lib/runtime/types/*.h lib/runtime/types/*.cpp lib/runtime/*.h lib/runtime/*.cpp lib/core/*.cpp lib/core/*.h lib/core/opcode/*.cpp lib/core/opcode/*.h lib/util/*.cpp lib/util/*.h lib/util/zip/*.cpp lib/util/zip/*.h lib/Modules/math/*.h lib/Modules/math/*.cpp lib/Modules/std/*.h lib/Modules/std/*.cpp lib/Modules/std.io/*.h lib/Modules/std.io/*.cpp
sudo cp bin/sharp /bin

# echo -n "Installing  standard Lib"
sudo rm -r /usr/include/sharp/
sudo mkdir /usr/include/sharp/
sudo cp -r lib/support/0.3.0/ /usr/include/sharp/

echo "sharp installed!"
